import type { Term } from "../terms.ts";

export const TERMS: Term[] = [
  { id: "pan", cat: "Camera", en: "Pan", ja: "パン",
    desc: "The camera turns left or right from a fixed spot. Everything slides by at the same speed.",
    ask: "Pan right slowly across the skyline over 3 seconds, at an even speed." },
  { id: "truck", cat: "Camera", en: "Truck", ja: "トラック",
    desc: "The camera itself moves sideways. Near things pass faster than far ones: parallax.",
    ask: "Truck left past the posts: the posts in front move fast, the hills behind move slowly." },
  { id: "tilt", cat: "Camera", en: "Tilt", ja: "ティルト",
    desc: "The camera turns up or down from a fixed spot, like nodding.",
    ask: "Tilt up from the street to the top of the tower over 3 seconds." },
  { id: "dolly-in", cat: "Camera", en: "Dolly in", ja: "ドリーイン",
    desc: "The camera moves toward the subject. It grows, and the space around it opens out.",
    ask: "Slow dolly in on the subject over 4 seconds, ending in a close-up." },
  { id: "dolly-zoom", cat: "Camera", en: "Dolly zoom", ja: "ドリーズーム",
    desc: "Dolly out while zooming in. The subject keeps its size while the background stretches. Also called the Vertigo effect.",
    ask: "Dolly zoom on the subject over 2 seconds: move back while zooming in, so the subject stays the same size and the background stretches." },
  { id: "whip-pan", cat: "Camera", en: "Whip pan", ja: "ホイップパン",
    desc: "A pan so fast the picture smears. Often used to cut from one scene to the next.",
    ask: "Whip pan from the first scene to the second in about 0.3 seconds, with motion blur." },
  { id: "rack-focus", cat: "Camera", en: "Rack focus", ja: "ピント送り",
    desc: "Focus moves from one subject to another at a different distance.",
    ask: "Rack focus from the cup in front to the person behind, over 1 second." },
  { id: "orbit", cat: "Camera", en: "Orbit", ja: "回り込み",
    desc: "The camera circles around the subject while keeping it in the center. The subject turns and the background slides behind it.",
    ask: "Orbit 90 degrees around the product over 3 seconds, keeping it centered, with an ease-in-out." },
  { id: "crash-zoom", cat: "Camera", en: "Crash zoom", ja: "クラッシュズーム",
    desc: "A very fast zoom onto one detail. It hits like a punch and is often played for comedy or shock.",
    ask: "Crash zoom onto the face in 0.15 seconds, hold for 0.8 seconds, then cut back to the wide shot." },
  { id: "camera-shake", cat: "Camera", en: "Camera shake", ja: "カメラシェイク",
    desc: "The whole frame jolts and jitters, then settles. It sells an impact, an explosion or a heavy landing.",
    ask: "On the impact, shake the camera up to 12 px for 0.4 seconds, decaying to still." },
  { id: "parallax", cat: "Camera", en: "Parallax", ja: "パララックス",
    desc: "Flat layers of artwork slide at different speeds, near ones fastest, so a 2D picture gains depth.",
    ask: "Split the landscape into 4 layers and slide them left, the front layer 4 times faster than the sky, over 4 seconds." },
  { id: "ken-burns", cat: "Camera", en: "Ken Burns", ja: "ケン・バーンズ",
    desc: "A slow pan and zoom over a still photo. It brings photos to life in documentaries and slideshows.",
    ask: "Slowly zoom the photo from 100% to 115% while panning toward the left face, over 5 seconds." },
];
