import type { Term } from "../terms.ts";

export const TERMS: Term[] = [
  { id: "twirl", cat: "Distortion", en: "Twirl", ja: "渦巻き",
    desc: "Turns the picture more at the centre than at the edge, so straight lines curl into a spiral.",
    ask: "Twirl the logo 360 degrees into a spiral over 0.6 seconds, then unwind it over the next 0.6 seconds." },
  { id: "wave-warp", cat: "Distortion", en: "Wave warp", ja: "ウェーブワープ",
    desc: "A sine wave runs through the layer and bends it as it passes. Good for flags, water and heat.",
    ask: "Run a wave warp through the stripes: 12 px high, 150 px long, one wave a second, left to right." },
  { id: "turbulent-displace", cat: "Distortion", en: "Turbulent displace", ja: "タービュレントディスプレイス",
    desc: "Pushes the pixels around with noise, so clean edges turn wobbly and organic.",
    ask: "Give the shape a turbulent displace of 20 px whose noise drifts slowly, so its edges boil softly." },
  { id: "displacement-map", cat: "Distortion", en: "Displacement map", ja: "ディスプレイスメントマップ",
    desc: "Moves each pixel by the brightness of another layer, the map. Where the map is bright, the picture is pushed.",
    ask: "Use a soft round blob as a displacement map and move it across the grid in 2 seconds, pushing the lines up to 25 px aside." },
  { id: "polar-coordinates", cat: "Distortion", en: "Polar coordinates", ja: "極座標",
    desc: "Wraps the layer around a centre: left to right becomes around, top to bottom becomes out to in. Straight bars turn into rings.",
    ask: "Wrap the bar chart into a radial chart with polar coordinates over 0.8 seconds, hold, then unwrap it." },
  { id: "ripple", cat: "Distortion", en: "Ripple", ja: "波紋",
    desc: "Rings of waves spread out from a point, like a drop in water, and warp what they pass.",
    ask: "Send a ripple out from the tap point: waves 60 px apart, 8 px high, fading out by the edge of the frame." },
  { id: "bend", cat: "Distortion", en: "Bend", ja: "ベンド",
    desc: "Curves a flat layer along one axis, like a sheet of paper or a banner bending.",
    ask: "Bend the banner into a smile and then a frown, about 60 degrees each way, over 2.6 seconds." },
  { id: "kaleidoscope", cat: "Distortion", en: "Kaleidoscope", ja: "万華鏡",
    desc: "Mirrors one wedge of the picture round a centre, so anything moving in it becomes a symmetric pattern.",
    ask: "Mirror one wedge into 8 segments, then let the shapes inside drift so the pattern keeps changing." },
  { id: "slit-scan", cat: "Distortion", en: "Slit-scan", ja: "スリットスキャン",
    desc: "Each row of the picture shows a slightly later moment, so moving things lean and smear.",
    ask: "Apply a slit-scan where the bottom row lags the top by 0.6 seconds, so the moving ball leans as it swings." },
  { id: "motion-tile", cat: "Distortion", en: "Motion tile", ja: "モーションタイル",
    desc: "Repeats a layer beyond its edges, so you can scroll a pattern forever without a seam.",
    ask: "Tile the pattern with motion tile and scroll it diagonally by one tile every 2.6 seconds, looping seamlessly." },
  { id: "radial-blur", cat: "Distortion", en: "Radial blur", ja: "ズームブラー",
    desc: "Smears the picture along lines out from the centre, as if the lens zoomed during the exposure. Peaking it on a cut makes the cut hit harder.",
    ask: "Ramp a radial blur up over the last 0.4 seconds of the shot, cut at the peak, then ramp it back down over the first 0.3 seconds of the next shot." },
];
