import type { Term } from "../terms.ts";

export const TERMS: Term[] = [
  { id: "match-cut", cat: "Editing", en: "Match cut", ja: "マッチカット",
    desc: "A cut between two shots joined by a matching shape or motion in the same place, so the eye carries over.",
    ask: "Cut from the ball to the setting sun, with both the same size in the same spot on screen." },
  { id: "jump-cut", cat: "Editing", en: "Jump cut", ja: "ジャンプカット",
    desc: "Cuts within one shot that skip time, so the subject pops from place to place. Fast and restless.",
    ask: "Cut out the pauses in the talking shot, every 0.6 seconds, so the speaker jumps a little each time." },
  { id: "j-cut", cat: "Editing", en: "J cut", ja: "Jカット",
    desc: "The sound of the next shot starts before its picture. You hear what is coming, then see it.",
    ask: "Start the next scene's audio 1 second before cutting to its picture." },
  { id: "l-cut", cat: "Editing", en: "L cut", ja: "Lカット",
    desc: "The sound of a shot carries on after the picture has cut to the next one.",
    ask: "Cut to the listener's reaction while the speaker's voice keeps going for 1.5 seconds." },
  { id: "smash-cut", cat: "Editing", en: "Smash cut", ja: "スマッシュカット",
    desc: "A sudden hard cut from a calm moment to a loud, contrasting one. The jolt is the point.",
    ask: "Hold the quiet shot for 2 seconds, then smash cut to the loud one with no transition." },
  { id: "split-screen", cat: "Editing", en: "Split screen", ja: "スプリットスクリーン",
    desc: "The frame splits to show two shots side by side at once, to compare them or to show two places at the same time.",
    ask: "Slide a divider in over 0.4 seconds and show the two shots side by side for 3 seconds." },
  { id: "cut-to-the-beat", cat: "Editing", en: "Cut to the beat", ja: "音ハメ",
    desc: "Cuts land exactly on the beats of the music, so the picture feels locked to the sound.",
    ask: "Cut to a new shot on every beat at 120 BPM, one cut each 0.5 seconds." },
  { id: "speed-ramp", cat: "Editing", en: "Speed ramp", ja: "スピードランプ",
    desc: "The playback speed changes smoothly within a shot, fast into slow motion at the key moment and fast again.",
    ask: "Play the jump at 2x, ramp down to 0.2x at the top for 1 second, then ramp back up to 2x." },
  { id: "freeze-frame", cat: "Editing", en: "Freeze frame", ja: "フリーズフレーム",
    desc: "The action stops on one frame, often with a flash and a caption, to introduce someone or mark a moment.",
    ask: "Freeze the frame mid-jump with a white flash, and pop in a name card for 1.5 seconds." },
];
