import type { Term } from "../terms.ts";

export const TERMS: Term[] = [
  { id: "particles", cat: "Generative", en: "Particles", ja: "パーティクル",
    desc: "Many small dots thrown from an emitter, each with its own speed and life, pulled by gravity and fading out. For sparks, dust, confetti and magic.",
    ask: "Spray orange particles up from the button on click: 80 of them, falling back under gravity and fading out within 1 second." },
  { id: "shatter", cat: "Generative", en: "Shatter", ja: "シャター",
    desc: "A shape breaks into shards that fly apart from a point of impact. Played backwards, the pieces come together.",
    ask: "Shatter the logo into about 30 shards from the left, then pull them back together over 0.8 seconds." },
  { id: "fractal-noise", cat: "Generative", en: "Fractal noise", ja: "フラクタルノイズ",
    desc: "Layers of soft noise at finer and finer scales, which make clouds, smoke and texture. Moving the layers makes it evolve.",
    ask: "Fill the background with slowly evolving grey fractal noise, like smoke, at 20% opacity." },
  { id: "flow-field", cat: "Generative", en: "Flow field", ja: "フローフィールド",
    desc: "Lines that follow a field of directions made from noise, like hair or wind. Changing the field slowly makes the lines swirl.",
    ask: "Draw 100 thin strands following a slowly changing noise flow field, with orange highlights running along them." },
  { id: "lightning", cat: "Generative", en: "Lightning", ja: "稲妻",
    desc: "A jagged, branching bolt between two points that redraws and flickers every frame.",
    ask: "Arc a flickering lightning bolt between the two terminals, with a new random shape every 2 frames." },
  { id: "audio-spectrum", cat: "Generative", en: "Audio spectrum", ja: "オーディオスペクトラム",
    desc: "Bars that rise and fall with the loudness of each frequency band. The low bars jump on the kick, the high ones on the hats.",
    ask: "Add a 32-bar audio spectrum along the bottom that reacts to the music, with peak caps that fall slowly." },
  { id: "plexus", cat: "Generative", en: "Plexus", ja: "プレクサス",
    desc: "Drifting points joined by lines when they come close, the lines fading with distance. A common look for networks and technology.",
    ask: "Float 40 points slowly and connect any two closer than 90 px with a line that fades as they part." },
  { id: "card-dance", cat: "Generative", en: "Card dance", ja: "カードダンス",
    desc: "The picture is cut into a grid of cards that flip one after another, often in a wave, to reveal the next picture.",
    ask: "Split the image into an 8 × 6 grid and flip the cards in a diagonal wave over 1 second to reveal the next slide." },
  { id: "scribble", cat: "Generative", en: "Scribble", ja: "スクリブル",
    desc: "A shape filled with quick hand-drawn hatching that is redrawn every other frame, so it boils like hand animation.",
    ask: "Fill the circle with an orange scribble that redraws at 12 fps with a slightly different stroke each time." },
];
