import type { Term } from "../terms.ts";

export const TERMS: Term[] = [
  { id: "key-light", cat: "Light", en: "Key light", ja: "キーライト", dark: true,
    desc: "The main light. Its direction sets the shape and the mood of the subject.",
    ask: "Light the product with one warm key light from the upper left." },
  { id: "rim-light", cat: "Light", en: "Rim light", ja: "リムライト", dark: true,
    desc: "A light from behind that traces the edge of the subject and lifts it off the background.",
    ask: "Add a rim light from behind so the silhouette separates from the dark background." },
  { id: "color-temperature", cat: "Light", en: "Color temperature", ja: "色温度",
    desc: "Warm light reads as evening or comfort, cool light as night or distance.",
    ask: "Shift the light from warm evening to cool night over 4 seconds." },
  { id: "glow", cat: "Light", en: "Glow", ja: "グロー", dark: true,
    desc: "Soft light that spreads past the edges of bright shapes. It makes them feel lit from inside.",
    ask: "Give the neon ring a soft orange glow that swells and fades once every 2 seconds." },
  { id: "lens-flare", cat: "Light", en: "Lens flare", ja: "レンズフレア", dark: true,
    desc: "Rings and streaks a bright light leaves inside a lens. The rings line up through the centre of the frame and move against the light.",
    ask: "Move the sun across the top of the frame over 3 seconds, with a lens flare whose rings slide through the centre." },
  { id: "light-leak", cat: "Light", en: "Light leak", ja: "光漏れ", dark: true,
    desc: "Warm washes of light that drift in from the edges, as if light got into the camera. Feels like film and memory.",
    ask: "Lay warm orange light leaks over the footage, drifting in from the left edge and fading out over 2 seconds." },
  { id: "god-rays", cat: "Light", en: "God rays", ja: "ゴッドレイ", dark: true,
    desc: "Beams of light from a bright source, made visible by haze or dust in the air.",
    ask: "Add soft god rays from the top left that sway slightly, with dust drifting through the beams." },
  { id: "drop-shadow", cat: "Light", en: "Drop shadow", ja: "ドロップシャドウ",
    desc: "A soft shadow under an object. Moving it further and blurring it more makes the object rise off the page.",
    ask: "On hover, lift the card 8 px over 0.3 seconds, growing its shadow from 4 px to 24 px blur." },
  { id: "long-shadow", cat: "Light", en: "Long shadow", ja: "ロングシャドウ",
    desc: "A flat, hard shadow that runs out from an icon at 45 degrees to the edge of its tile. A flat-design look.",
    ask: "Grow a long shadow from the icon to the bottom-right corner of its tile over 0.6 seconds." },
  { id: "light-sweep", cat: "Light", en: "Light sweep", ja: "ライトスイープ",
    desc: "A band of light glides across a surface, as if it caught the light. Used to make logos and cards feel glossy.",
    ask: "Sweep a diagonal highlight across the card from left to right in 0.7 seconds, once every 2.5 seconds." },
  { id: "bokeh", cat: "Light", en: "Bokeh", ja: "玉ボケ", dark: true,
    desc: "Points of light far out of focus turn into soft round discs. Behind sharp type they add depth and a warm, festive glow.",
    ask: "Fill the background with soft orange bokeh, discs 30 to 90 px across that drift slowly and pulse, behind a sharp white title." },
  { id: "star-glint", cat: "Light", en: "Star glint", ja: "クロスフィルター", dark: true,
    desc: "A point of light flares into a four- or six-pointed star, as through a cross filter, then shrinks away. It turns a highlight into a sparkle.",
    ask: "Flare a 4-point star glint on the gem's top corner to 120 px in 0.2 seconds, turn it 20 degrees, and shrink it away over 0.5 seconds." },
];
