import type { Term } from "../terms.ts";

export const TERMS: Term[] = [
  { id: "ease-in-out", cat: "Motion", en: "Ease in-out", ja: "イーズインアウト",
    desc: "Starts slow, speeds up, slows into place. Most camera and UI moves use it.",
    ask: "Move the card across with an ease-in-out over 0.8 seconds." },
  { id: "overshoot", cat: "Motion", en: "Overshoot", ja: "オーバーシュート",
    desc: "Passes the target, then settles back. Feels springy and alive.",
    ask: "Slide the badge in with a slight overshoot, settling in 0.6 seconds." },
  { id: "anticipation", cat: "Motion", en: "Anticipation", ja: "予備動作",
    desc: "A small move the other way before the main one, so the eye knows it is coming.",
    ask: "Before the arrow shoots right, pull it back a little for 0.2 seconds." },
  { id: "stagger", cat: "Motion", en: "Stagger", ja: "ずらし",
    desc: "The same motion, started a little later for each item.",
    ask: "Bring the bars up one after another, 60 ms apart." },
  { id: "squash-and-stretch", cat: "Motion", en: "Squash and stretch", ja: "つぶしと伸ばし",
    desc: "The shape deforms with speed and impact, while its volume stays the same.",
    ask: "Bounce the ball with squash on impact and a little stretch while falling." },
  { id: "follow-through", cat: "Motion", en: "Follow-through", ja: "フォロースルー",
    desc: "When the body stops, its loose parts keep going, swing back and settle. It shows weight and momentum.",
    ask: "When the character stops, let the antennae carry on forward and settle over 0.5 seconds." },
  { id: "bounce", cat: "Motion", en: "Bounce", ja: "バウンス",
    desc: "Each bounce is lower and shorter than the last, until the object comes to rest. It reads as a drop with real weight.",
    ask: "Drop the ball onto the floor and let it bounce four times, each about a third as high, settling within 1.5 seconds." },
  { id: "elastic", cat: "Motion", en: "Elastic", ja: "エラスティック",
    desc: "Overshoots and swings back several times, like a spring, before it settles. Good for pops and playful UI.",
    ask: "Pop the button in with an elastic scale from 0 to 100%, wobbling three times and settling in 0.8 seconds." },
  { id: "wiggle", cat: "Motion", en: "Wiggle", ja: "ウィグル",
    desc: "A smooth random wobble in position or rotation that never repeats exactly. It adds a handheld or nervous energy.",
    ask: "Wiggle the sticker 3 times a second, up to 20 px and 5 degrees, and keep it going for the whole shot." },
  { id: "on-twos", cat: "Motion", en: "On twos", ja: "コマ打ち",
    desc: "Each pose is held for two or more frames, so the motion moves in visible steps. It gives a hand-made, animated feel.",
    ask: "Animate the character on twos: hold each pose for 2 frames at 24 fps." },
  { id: "sine-wave", cat: "Motion", en: "Sine wave", ja: "サイン波",
    desc: "A smooth up and down that repeats forever. Offset each item's timing and a row of them becomes a wave.",
    ask: "Bob the dots up and down 20 px on a 2-second sine, each one 0.1 seconds behind the last." },
  { id: "motion-path", cat: "Motion", en: "Motion path", ja: "モーションパス",
    desc: "The object travels along a drawn curve instead of a straight line, turning to face the way it moves.",
    ask: "Fly the paper plane along a figure-eight path over 3 seconds, auto-oriented to the path." },
  { id: "motion-blur", cat: "Motion", en: "Motion blur", ja: "モーションブラー",
    desc: "A fast object smears along its path, the way it would with a camera shutter open. Fast moves look smooth instead of jumpy.",
    ask: "Add motion blur with a 180-degree shutter to the fast whip of the logo." },
];
