import type { Term } from "../terms.ts";

export const TERMS: Term[] = [
  { id: "trim-paths", cat: "Shape", en: "Trim paths", ja: "トリムパス",
    desc: "A stroke draws itself along its path, then its tail follows the head off. The basic way to animate a line.",
    ask: "Draw the underline on with trim paths over 0.5 seconds, hold, then trim it off from the start over 0.4 seconds." },
  { id: "stroke-width", cat: "Shape", en: "Stroke width", ja: "線幅アニメーション",
    desc: "The thickness of a line changes over time. Thin lines feel light, thick ones feel heavy and loud.",
    ask: "Pulse the ring's stroke width from 4 px to 24 px and back, once every 1.2 seconds." },
  { id: "shape-morph", cat: "Shape", en: "Shape morph", ja: "シェイプモーフ",
    desc: "One shape turns smoothly into another, point by point. Good for icons that change state.",
    ask: "Morph the circle into a square and then a star, 0.5 seconds each with an ease-in-out, holding each shape briefly." },
  { id: "repeater", cat: "Shape", en: "Repeater", ja: "リピーター",
    desc: "Copies of one shape, each turned, scaled or moved a little more than the last. One shape becomes a pattern.",
    ask: "Repeat the petal 12 times, 30 degrees apart and each 4% smaller, fanning out from one petal over 0.8 seconds." },
  { id: "offset-paths", cat: "Shape", en: "Offset paths", ja: "パスのオフセット",
    desc: "Copies of an outline, grown outward by a set distance. Animated, they ripple out from the shape.",
    ask: "Send offset copies of the star's outline outward every 0.3 seconds, 14 px apart, fading as they grow." },
  { id: "wiggle-paths", cat: "Shape", en: "Wiggle paths", ja: "パスのウィグル",
    desc: "The points of a path wander a little at random, so a clean shape looks hand-drawn and alive.",
    ask: "Wiggle the outline's points by up to 10 px, about two wiggles a second." },
  { id: "pucker-and-bloat", cat: "Shape", en: "Pucker and bloat", ja: "パンク・膨張",
    desc: "The edges of a shape bend in toward its center or puff out, while its corners stay put.",
    ask: "Pucker the hexagon into a star, then bloat it into a flower, 0.6 seconds each." },
  { id: "marching-ants", cat: "Shape", en: "Marching ants", ja: "破線アニメーション",
    desc: "Dashes that flow along a line by moving the dash offset. Shows a route, a flow or a selection.",
    ask: "Draw the route as a dashed line and move the dashes toward the pin at 40 px per second." },
  { id: "burst", cat: "Shape", en: "Burst", ja: "バースト",
    desc: "Short lines shoot out from a point and vanish, like a spark. Marks a click, a like or a hit.",
    ask: "When the button is tapped, shoot 12 short lines out from its center and trim them off within 0.4 seconds." },
  { id: "metaballs", cat: "Shape", en: "Metaballs", ja: "メタボール",
    desc: "Round blobs that melt together when they come close and stretch apart like goo when they leave.",
    ask: "Let two blobs drift together and merge like liquid, then pull apart, over 2.5 seconds." },
  { id: "extrude", cat: "Shape", en: "Extrude", ja: "押し出し",
    desc: "A flat shape is pushed back into depth, so it gains side walls and turns into a solid you can tilt.",
    ask: "Extrude the flat star 40 px deep over 0.6 seconds while tilting it 30 degrees so its sides show, then flatten it back." },
];
