import type { Term } from "../terms.ts";

export const TERMS: Term[] = [
  { id: "film-grain", cat: "Texture", en: "Film grain", ja: "フィルムグレイン",
    desc: "Fine noise that changes every frame, with a little flicker and weave. Clean digital pictures feel shot on film.",
    ask: "Add a light film grain over the whole video, new grain every frame, at about 8% opacity." },
  { id: "grunge", cat: "Texture", en: "Grunge", ja: "グランジ",
    desc: "Worn, eroded edges, specks and stains, as if the shape was printed and handled. Takes the shine off vector art.",
    ask: "Give the logo a grunge texture: rough edges and worn specks, swapping the texture every 3 frames." },
  { id: "halftone", cat: "Texture", en: "Halftone", ja: "ハーフトーン",
    desc: "Tone becomes a grid of dots, big where it is dark and small where it is light, like print.",
    ask: "Turn the photo into an orange and black halftone with 10 px dots, wiping in from the left over 1 second." },
  { id: "duotone", cat: "Texture", en: "Duotone", ja: "デュオトーン",
    desc: "The picture is mapped to two colours: one for the shadows, one for the highlights.",
    ask: "Make the footage a duotone, navy in the shadows and orange in the highlights." },
  { id: "posterize", cat: "Texture", en: "Posterize", ja: "ポスタライズ",
    desc: "Smooth gradients snap into a few flat bands of colour. Fewer levels look bolder and more graphic.",
    ask: "Posterize the sphere, stepping from smooth down to 3 levels and back, one step every 0.3 seconds." },
  { id: "line-boil", cat: "Texture", en: "Line boil", ja: "ラインボイル",
    desc: "Hand-drawn outlines are redrawn slightly differently every other frame, so a still drawing stays alive.",
    ask: "Make the outlines boil: redraw them with a 2 px wobble on twos, 12 times a second." },
  { id: "vignette", cat: "Texture", en: "Vignette", ja: "ビネット",
    desc: "The corners and edges of the frame darken, pulling the eye to the centre.",
    ask: "Add a soft vignette that darkens the corners by 40%, breathing slowly over 3 seconds." },
  { id: "find-edges", cat: "Texture", en: "Find edges", ja: "輪郭検出",
    desc: "Keeps only the edges of the picture as lines and drops the fills, so a photo turns into a drawing.",
    ask: "Fade the fills out over 0.5 seconds so only the detected edges remain, then fade them back." },
  { id: "rgb-split", cat: "Texture", en: "RGB split", ja: "RGB分離",
    desc: "The colour channels slip apart into coloured fringes, then snap back. Reads as energy, impact or a broken signal.",
    ask: "On the hit, split the RGB channels 12 px apart and snap them back together in 0.3 seconds." },
  { id: "glitch", cat: "Texture", en: "Glitch", ja: "グリッチ",
    desc: "Short bursts of digital error: slices of the picture jump sideways, blocks break and colours go wrong.",
    ask: "Add two short glitch bursts, 0.2 seconds each, with sliced offsets and colour errors, clean in between." },
  { id: "scanlines", cat: "Texture", en: "Scanlines", ja: "走査線", dark: true,
    desc: "Thin horizontal lines and a slow rolling bar, like an old CRT screen.",
    ask: "Overlay scanlines every 4 px and a soft bright bar rolling down the screen every 2.5 seconds." },
  { id: "vhs", cat: "Texture", en: "VHS look", ja: "VHS風",
    desc: "Soft picture, colour bleeding sideways, a noisy tracking band and the tape's on-screen text.",
    ask: "Give the clip a VHS look: chroma bleed, a tracking noise band near the bottom, slight jitter and a PLAY label." },
  { id: "datamosh", cat: "Texture", en: "Datamosh", ja: "データモッシュ",
    desc: "At a cut, the old picture's blocks are pushed around by the new shot's motion and smear into it.",
    ask: "Datamosh the cut: let the first shot's pixels smear with the second shot's motion for 1 second before it clears." },
  { id: "pixelate", cat: "Texture", en: "Pixelate", ja: "モザイク",
    desc: "The picture breaks into square blocks of flat colour. Bigger blocks hide more.",
    ask: "Pixelate the frame in steps, 4, 10, 20 then 50 px blocks, and back to sharp." },
  { id: "dither", cat: "Texture", en: "Dither", ja: "ディザリング",
    desc: "Shades are faked with a pattern of only two colours, the look of 1-bit screens and old printers.",
    ask: "Render the scene as 1-bit black and white with an ordered Bayer dither, pixels 4 px wide." },
];
