import type { Term } from "../terms.ts";

export const TERMS: Term[] = [
  { id: "nuki", cat: "Transition", en: "Nuki (pull)", ja: "抜き",
    desc: "The kamishibai card change: the picture is pulled out sideways to show the next. Pulled fast, slowly, or stopped halfway.",
    ask: "Change scenes like a kamishibai card: pull the picture out to the side, stop halfway for a beat, then pull it out." },
  { id: "crossfade", cat: "Transition", en: "Crossfade", ja: "ディゾルブ",
    desc: "One shot fades into the next, and for a moment both are visible.",
    ask: "Crossfade to the next shot over 0.6 seconds." },
  { id: "wipe", cat: "Transition", en: "Wipe", ja: "ワイプ",
    desc: "A moving edge replaces one shot with the next.",
    ask: "Wipe left to right to the next shot over 0.5 seconds." },
  { id: "iris", cat: "Transition", en: "Iris", ja: "アイリス",
    desc: "A circle opens or closes on the picture.",
    ask: "Iris out on the character to end the scene." },
  { id: "push", cat: "Transition", en: "Push", ja: "プッシュ",
    desc: "The next shot pushes the current one out of the frame.",
    ask: "Push the next slide in from the right over 0.5 seconds." },
  { id: "slide", cat: "Transition", en: "Slide", ja: "スライド",
    desc: "The next shot slides in over the current one, which stays still underneath. Unlike a push, only the new shot moves.",
    ask: "Slide the next shot in from the right over the current one in 0.5 seconds, with a soft shadow on its edge." },
  { id: "zoom-transition", cat: "Transition", en: "Zoom transition", ja: "ズームトランジション",
    desc: "The camera rushes into the shot, and the next shot arrives from far away and lands. The speed hides the cut.",
    ask: "Zoom into the logo over 0.3 seconds with zoom blur, cut, and land the next shot from 30% to 100% in 0.3 seconds." },
  { id: "venetian-blinds", cat: "Transition", en: "Venetian blinds", ja: "ブラインド",
    desc: "The picture splits into stripes that turn open like the slats of a blind, one after another, to show the next shot.",
    ask: "Change shots with 6 horizontal blinds opening top to bottom, 50 ms apart, over 0.6 seconds." },
  { id: "clock-wipe", cat: "Transition", en: "Clock wipe", ja: "時計回りワイプ",
    desc: "The next shot sweeps in around the centre, like a clock hand going once round.",
    ask: "Clock-wipe to the next shot from 12 o'clock, clockwise, over 0.8 seconds." },
  { id: "gradient-wipe", cat: "Transition", en: "Gradient wipe", ja: "グラデーションワイプ",
    desc: "The next shot appears where a grey map is darkest first, then spreads to the lighter areas. Any map works: noise, clouds, a gradient.",
    ask: "Gradient-wipe to the next shot over 1 second, following a cloudy noise map with a soft edge." },
  { id: "shape-transition", cat: "Transition", en: "Shape transition", ja: "シェイプトランジション",
    desc: "Coloured shapes sweep across and cover the frame, and the next shot is behind them as they leave.",
    ask: "Sweep three slanted bars in the brand colours across from the left, 80 ms apart, and switch shots while they cover the frame." },
  { id: "liquid-transition", cat: "Transition", en: "Liquid transition", ja: "リキッドトランジション",
    desc: "The next shot floods in like a liquid, with a wavy, gooey edge. It feels playful and soft.",
    ask: "Flood the next shot up from the bottom with a wavy liquid edge over 0.8 seconds, an orange layer leading by 0.15 seconds." },
];
