import type { Term } from "../terms.ts";

export const TERMS: Term[] = [
  { id: "kinetic-typography", cat: "Type", en: "Kinetic typography", ja: "キネティックタイポグラフィ",
    desc: "Words land one per beat, each at its own size and place, so the type itself carries the rhythm.",
    ask: "Punch the three words in on the beat, 0.4 seconds apart, each with a small overshoot, then hold." },
  { id: "typewriter", cat: "Type", en: "Typewriter", ja: "タイプライター",
    desc: "Characters appear one at a time behind a cursor, as if someone is typing them.",
    ask: "Type the line at about 12 characters a second, with a blinking cursor that stays for 1 second after." },
  { id: "per-character-animation", cat: "Type", en: "Per-character animation", ja: "1文字ずつ",
    desc: "Each letter moves on its own, started a little after the one before, so a word arrives as a wave.",
    ask: "Bring the title in letter by letter, each rising 20 px and fading in over 0.4 seconds, 40 ms apart." },
  { id: "mask-reveal", cat: "Type", en: "Mask reveal", ja: "マスクリビール",
    desc: "Lines of text slide up from behind an invisible edge, so they seem to rise out of the page.",
    ask: "Reveal each line by sliding it up from behind a mask over 0.5 seconds, 100 ms apart." },
  { id: "text-scramble", cat: "Type", en: "Text scramble", ja: "テキストスクランブル",
    desc: "Random characters flicker in each slot, then settle into the real word from left to right.",
    ask: "Scramble the word in, resolving one letter every 60 ms, with the random glyphs changing 15 times a second." },
  { id: "tracking", cat: "Type", en: "Tracking", ja: "トラッキング",
    desc: "The space between all the letters opens or closes. A slow open makes a title feel calm and wide.",
    ask: "Open the title's tracking from 0 to 0.5 em over 2 seconds with an ease-in-out." },
  { id: "write-on", cat: "Type", en: "Write-on", ja: "手書きアニメーション",
    desc: "A stroke draws itself along the path of the letters, like a pen writing them.",
    ask: "Write the signature on along its path over 1.5 seconds, with a slight ease-out at the end." },
  { id: "text-on-a-path", cat: "Type", en: "Text on a path", ja: "パス上文字",
    desc: "Letters follow a curve, each turned to the direction of the line, and can travel along it.",
    ask: "Set the tagline on the wave and slide it along the path at 80 px a second." },
  { id: "variable-font", cat: "Type", en: "Variable font", ja: "バリアブルフォント",
    desc: "One font file with a weight axis, so the type can thin or thicken smoothly instead of jumping between styles.",
    ask: "Animate the heading's weight from 200 to 900 and back over 2.5 seconds." },
  { id: "count-up", cat: "Type", en: "Count-up", ja: "カウントアップ",
    desc: "A number rolls up to its value, digit by digit like an odometer, then holds.",
    ask: "Roll the number from 0 up to 1,280 over 1.5 seconds with an ease-out, then hold it." },
  { id: "fly-through", cat: "Type", en: "Fly-through", ja: "フライスルー",
    desc: "A word rushes toward the viewer from far away and passes the camera, its letters growing past the edges of the frame. The next word follows right behind.",
    ask: "Fly each word in from far back and through the camera over 1.6 seconds, speeding up as it nears, with the next word 0.9 seconds behind." },
];
